<?php
include_once "config.php";

define("NOTHING_FOUND",  0);
define("SEARCH",         1);
define("UPDATE",         2);
define("INSERT",         3);
define("DELETE",         4);
/**
 * Searches for entries in the database that match the given search query.
 *
 * @param $search The search query to match against entries in the database.
 *
 * @access public
 * @return int Returns 0 if nothing is found, otherwise, returns the results.
 */
function Search($search) {
    try {
        include_once "config.php";

        $db = new PDO(
            "mysql:host=" . DBHOST . "; dbname=" . DBNAME . ";charset=utf8",
            DBUSER,
            DBPASS
        );

        $select_query = "SELECT Users.UserID, Users.FirstName, Users.LastName, Users.Username, Users.Email, Websites.WebsiteID, Websites.WebsiteName, Websites.WebsiteURL, Passwords.PasswordID, Passwords.Password, Passwords.Comment, Passwords.Timestamp FROM Users
                         LEFT JOIN Passwords ON Users.UserID = Passwords.UserID
                         LEFT JOIN Websites ON Passwords.WebsiteID = Websites.WebsiteID
                         WHERE Users.Username LIKE \"%{$search}%\" OR Passwords.Password LIKE \"%{$search}%\" OR Websites.WebsiteID LIKE \"%{$search}%\" OR Websites.WebsiteName LIKE \"%{$search}%\"";

        $statement = $db->prepare($select_query);
        $statement->execute();

        if (count($statement->fetchAll()) == 0) {
            return 0;
        } else {
            echo "        </tbody>\n";
            echo "      </table>\n";
            echo "      <table>\n";
            echo "        <thead>\n";
            echo "          <tr>\n";
            echo "        <th>User ID</th>\n";
            echo "        <th>First Name</th>\n";
            echo "        <th>Last Name</th>\n";
            echo "        <th>Username</th>\n";
            echo "        <th>Email</th>\n";
            echo "        <th>Website ID</th>\n";
            echo "        <th>Website Name</th>\n";
            echo "        <th>Website URL</th>\n";
            echo "        <th>Password ID</th>\n";
            echo "        <th>Password</th>\n";
            echo "        <th>Comment</th>\n";
            echo "        <th>Timestamp</th>\n";
            echo "          </tr>\n";
            echo "        </thead>\n";
            echo "        <tbody>\n";

            foreach ($db->query($select_query)as $row) {
                echo "          <tr>\n";
                echo "            <td>" . (isset($row[0]) ? htmlspecialchars($row[0]) : '') . "</td>\n";
                echo "            <td>" . (isset($row[1]) ? htmlspecialchars($row[1]) : ''). "</td>\n";
                echo "            <td>" . (isset($row[2]) ? htmlspecialchars($row[2]) : ''). "</td>\n";
                echo "            <td>" . (isset($row[3]) ? htmlspecialchars($row[3]) : ''). "</td>\n";
                echo "            <td>" . (isset($row[4]) ? htmlspecialchars($row[4]) : ''). "</td>\n";
                echo "            <td>" . (isset($row[5]) ? htmlspecialchars($row[5]) : ''). "</td>\n";
                echo "            <td>" . (isset($row[6]) ? htmlspecialchars($row[6]) : ''). "</td>\n";
                echo "            <td>" . (isset($row[7]) ? htmlspecialchars($row[7]) : ''). "</td>\n";
                echo "            <td>" . (isset($row[8]) ? htmlspecialchars($row[8]) : ''). "</td>\n";
                echo "            <td>" . (isset($row[9]) ? htmlspecialchars($row[9]) : ''). "</td>\n";
                echo "            <td>" . (isset($row[10]) ? htmlspecialchars($row[10]) : '') . "</td>\n";
                echo "            <td>" . (isset($row[11]) ? htmlspecialchars($row[11]) : '') . "</td>\n";
                echo "          </tr>\n";
            }

            echo "         </tbody>\n";
            echo "      </table>\n";
        }
    } catch (PDOException $e) {
        echo '<p>The following message was generated by function <code>search</code>:</p>' . "\n";
        echo '<p id="error">' . $e->getMessage() . '</p>' . "\n";
        echo "<p>There are a few reasons for this. Perhaps the database doesn’t exist or wasn’t mounted. Does the volume/drive containing the database have read and write permissions?</p>\n";
        echo '<p>Click <a href="./">here</a> to go back.</p>';

        exit;
    }
}
/**
 * Deletes entries from the database based on the provided attribute and value.
 *
 * @param $attribute The attribute to match for deletion.
 * @param $value     The value of the attribute to match for deletion.
 *
 * @access public
 * @return void
 */
function Delete($attribute, $value) {
    try {
        include_once "config.php";

        $db = new PDO(
            "mysql:host=" . DBHOST . "; dbname=" . DBNAME . ";charset=utf8",
            DBUSER,
            DBPASS
        );

        $db->beginTransaction();

        $getWebsiteIDQuery = "SELECT WebsiteID FROM Websites WHERE $attribute = :value";
        $websiteIDStatement = $db->prepare($getWebsiteIDQuery);
        $websiteIDStatement->bindParam(':value', $value);
        $websiteIDStatement->execute();
        $websiteID = $websiteIDStatement->fetchColumn();

        if (!$websiteID) {
            echo '<div id="error">Entry not found.</div>' . "\n";
            return;
        }

        $deletePasswordsQuery = "DELETE FROM Passwords WHERE WebsiteID = :websiteID";
        $passwordsStatement = $db->prepare($deletePasswordsQuery);
        $passwordsStatement->bindParam(':websiteID', $websiteID);
        $passwordsStatement->execute();

        $deleteWebsitesQuery = "DELETE FROM Websites WHERE WebsiteID = :websiteID";
        $websitesStatement = $db->prepare($deleteWebsitesQuery);
        $websitesStatement->bindParam(':websiteID', $websiteID);
        $websitesStatement->execute();

        $deleteUsersQuery = "DELETE FROM Users WHERE UserID = :websiteID";
        $usersStatement = $db->prepare($deleteUsersQuery);
        $usersStatement->bindParam(':websiteID', $websiteID);
        $usersStatement->execute();

        $db->commit();
        echo '<div id="success">Entry deleted successfully.</div>' . "\n";
    } catch (PDOException $e) {
        $db->rollBack();
        echo '<div id="error">Error deleting entry. ' . $e->getMessage() . '</div>' . "\n";
    }
}
/**
 * Inserts a new entry into the database with the provided values.
 *
 * @param $siteName   The name of the website.
 * @param $URL        The URL of the website.
 * @param $Email      The email associated with the user.
 * @param $FirstName  The first name of the user.
 * @param $LastName   The last name of the user.
 * @param $Username   The username associated with the user.
 * @param $Password   The password associated with the user.
 * @param $comment    Additional comments or information.
 *
 * @access public
 * @return void
 */
function Insert($siteName, $URL, $Email, $FirstName, $LastName, $Username, $Password, $comment) {

    try {
        include_once "config.php";

        $db = new PDO(
            "mysql:host=" . DBHOST . "; dbname=" . DBNAME . ";charset=utf8",
            DBUSER,
            DBPASS
        );
        $db->exec("SET block_encryption_mode = 'aes-256-cbc'");
        $db->exec("SET @key_str = UNHEX(SHA2('Shmooba', 512))");
        $db->exec("SET @init_vector = RANDOM_BYTES(16)");

        $insertWebsiteQuery = "INSERT INTO Websites (WebsiteName, WebsiteURL) VALUES (:siteName, :URL)";
        $webstatement = $db->prepare($insertWebsiteQuery);
        $webstatement->execute(
            array(
                'siteName' => $siteName,
                'URL'  => $URL
            )
        );

        $webID = $db->lastInsertId();

        $insertUserQuery = "INSERT INTO Users (Email, FirstName, LastName, Username) VALUES (:Email, :FirstName, :LastName, :Username)";
        $userstatement = $db->prepare($insertUserQuery);
        $userstatement->execute(
            array(
                'Email'     => $Email,
                'FirstName' => $FirstName,
                'LastName'  => $LastName,
                'Username'  => $Username
            )
        );

        $userID = $db->lastInsertId();

        $insertPasswordQuery = "INSERT INTO Passwords (UserID, WebsiteID, Password, Comment) VALUES (:userID, :webID, AES_ENCRYPT(:Password, @key_str, @init_vector), :comment)";
        $passwordStatement = $db->prepare($insertPasswordQuery);
        $passwordStatement->execute(
            array(
                'userID'      => $userID,
                'webID'   => $webID,
                'Password'=> $Password,
                'comment'     => $comment
            )
        );

        echo '<div id="success">New entry added successfully.</div>' . "\n";
    } catch (PDOException $e) {
        echo '<div id="error">Error adding new entry. ' . $e->getMessage() . '</div>' . "\n";
    }
}
/**
 * Updates a specific attribute in the database based on the provided parameters.
 *
 * @param $current_attribute The attribute to update.
 * @param $new_attribute     The new value for the attribute.
 * @param $query_attribute   The attribute to use for the WHERE clause.
 * @param $pattern           The value to match in the WHERE clause.
 *
 * @access public
 * @return void
 */
function Update($current_attribute, $new_attribute, $query_attribute, $pattern) {
    try {
        $db = new PDO(
            "mysql:host=" . DBHOST . "; dbname=" . DBNAME . ";charset=utf8",
            DBUSER,
            DBPASS
        );

        $db -> query("UPDATE Websites SET {$current_attribute}=\"{$new_attribute}\" WHERE {$query_attribute}=\"{$pattern}\"");
    } catch( PDOException $e ) {
        echo '<p>The following message was generated by function <code>update</code>:</p>' . "\n";
        echo '<p id="error">' . $e -> getMessage() . '</p>' . "\n";

        exit;
    }
}







